### PR TITLE
Support usage of CpsTable

### PR DESCRIPTION
**Pull request by lukasmatta**

### CODE REVIEW

**Comment by fateeand** [comment]
The only suggestion is to use 
```
:root {
  --cps-mdoc-viewer-primary: var(--cps-color-calm);
  --cps-mdoc-viewer-secondary: var(--cps-color-prepared);
}
```
because of cps-table

**Comment by lukasmatta** [comment]
Do you mean to align `cps-table` coloring with the primary and secondary color? I started doing it, but then realized, it would be more effective to first make `cps-ui-kit` support theming and then just use `--cps-mdoc-viewer-primary/secondary` in the theme.

By theming in the `cps-ui-kit` I mean something like we are doing in this library - let the users define primary/secondary color and use those colors and their shades in the components. We can implement that gradually, so once `CpsTableComponent` will support it, it can be updated in this library.

**Comment by fateeand** [comment]
> Do you mean to align `cps-table` coloring with the primary and secondary color? I started doing it, but then realized, it would be more effective to first make `cps-ui-kit` support theming and then just use `--cps-mdoc-viewer-primary/secondary` in the theme.
> 
> By theming in the `cps-ui-kit` I mean something like we are doing in this library - let the users define primary/secondary color and use those colors and their shades in the components. We can implement that gradually, so once `CpsTableComponent` will support it, it can be updated in this library.

I mean exactly what I wrote above:
in `styles.scss` use
```
:root {
  --cps-mdoc-viewer-primary: var(--cps-color-calm);
  --cps-mdoc-viewer-secondary: var(--cps-color-prepared);
}
```

Until cps-ui-kit will support custom colors (which is not going to happen soon), use `--cps-color-calm` and `--cps-color-prepared` as primary and secondary colors in this library example app.

**Comment by lukasmatta** [comment]
ahaa, I see now, thanks for explaining, colors are replaced now

**Review by fateeand — APPROVED** [review]

**Pull request merged**
